<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(EnableAutoCad2016)' == 'true'">net45;net8.0</TargetFrameworks>
    <AssemblyName>Codex.AutoCAD.Contracts</AssemblyName>
    <RootNamespace>Codex.AutoCAD.Contracts</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <AutomaticallyUseReferenceAssemblyPackages Condition="'$(EnableAutoCad2016)' == 'true'">false</AutomaticallyUseReferenceAssemblyPackages>
  </PropertyGroup>
  <ItemGroup Condition="'$(EnableAutoCad2016)' == 'true'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net45" Version="[1.0.3]">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime;build;native;contentfiles;analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
