<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <PlatformTarget>x64</PlatformTarget>
    <AutoCad2025Dir Condition="'$(AutoCad2025Dir)' == ''">D:\Autodesk\Auto CAD\AutoCAD2025\AutoCAD 2025</AutoCad2025Dir>
  </PropertyGroup>
</Project>
